name: build
on:
  push:
    branches:
    - "**"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - run: go test
      - uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist
